version: '3'
services:
  jekyll:
    image: starefossen/github-pages
    #environment:
      #- "JEKYLL_GITHUB_TOKEN:${JEKYLL_GITHUB_TOKEN}"
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - ./docs:/usr/src/app
    tty: true